print "The result of True and True :\t\t\t\t\t%r" % (True and True)
print "The result of False and True :\t\t\t\t\t%r" % (False and True)
print "The result of 1 == 1 and 2== 1 :\t\t\t\t%r" % (1==1 and 2==1)
print "The result of 'test' == 'test' :\t\t\t\t%r" % ("test" == "test")
print "The result 1==1 or 2!=1 :\t\t\t\t\t%r" % (1==1 or 2!=1)
print "True and 1==1 :\t\t\t\t\t\t\t%r" % (True and 1==1)
print "False and 0!=0 :\t\t\t\t\t\t%r" % (False and 0!=0)
print "True or 1==1 :\t\t\t\t\t\t\t%r" % (True or 1==1)
print "'test' == testing :\t\t\t\t\t\t%r" % ("test" == "testing")
print "1!=0 and 2==1 :\t\t\t\t\t\t\t%r" % (1!=0 and 2==1)
print "'test' != 'testing':\t\t\t\t\t\t%r" % ("test" != "testing")
print "'test' == 1 :\t\t\t\t\t\t\t%r" % ("test" == 1)
print "not (True and False) :\t\t\t\t\t\t%r" % (not(True and False))
print "not(1==1 and 0!=1) :\t\t\t\t\t\t%r" % (not(1==1 and 0!=1))
print "not(10==1 or 1000=1000) :\t\t\t\t\t%r" % (not(10==1 or 1000==1000))
print "not(1!=10) or 3==4 :\t\t\t\t\t\t%r" % (not(1!=10) or 1000==1000)
print "not ('testing' == 'testing' and 'Sean' == 'Cool Guy') : \t%r" % (not ("testing" == "testing" and "Sean" == "Cool Guy")) 
print "1==1 and (not('testing'==1 or 1==0)) :\t\t\t\t%r" % (1==1 and (not("testing" == 1 or 1==0)))
print "'chunky' == 'bacon' and (not(3==4 or 3==3)) :\t\t\t%r" % ("chunky"=="bacon" and not(3==4 or 3==3))
print "3==3 and (not('testing' == 'testing' or 'Python' == 'Fun')) :\t%r" % (3==3 and not("testing"=="testing" or "Python" == "Fun"))